#!/usr/bin/env sh
#
# Create and rename one font style according to the specs
#
# Example invocation:
#   do_generate 01 --powerline --mono MonoLisa-Regular.ttf XMonoLisa.ttf XMonoLisa
#
# No parameters are checked, but they are:
# 1: Number of logfile
# 2: Conversion spec #1
# 3: Conversion spec #2
# 4: Input font file name
# 5: Output font file name
# 6: Font family name

OURVERSION="1.805"

set -e

if [ "$#" -ne 6 ]; then
    exit 1
fi

rm -f M*.ttf
fontforge -script font-patcher --careful "${3}" --custom SomeExtraSymbols.otf --no-progressbars "ttf/${4}" "${2}" | tee "process${1}.log"

if [ -z "${OURVERSION}" ]; then
    # Github CI sets this variable, but this can be useful for manual calls:
    OURVERSION="${OURVERSION}"
fi
fontforge rename-font --orig "ttf/${4}" --input M*.ttf --output "${5}" --version "${OURVERSION}" --name "${6}"
