#!/usr/bin/env python
# coding=utf8

import os.path
import fontforge
from argparse import ArgumentParser

from name_parser import FontnameParser

# Setup and parse the comand-line arguments
parser = ArgumentParser()
parser.add_argument("--input", help="input file name")
parser.add_argument("--orig", help="original font filename")
parser.add_argument("--output", help="output file name")
parser.add_argument("--name", help="preferred family name")
parser.add_argument("--version", help="text to add to the existing version")
args = parser.parse_args()

SIL_TABLE = [(".*", args.name)]  # Rename anything

fname = os.path.splitext(os.path.basename(args.orig))[0]
n = FontnameParser(fname)
n.add_name_substitution_table(SIL_TABLE)
n.set_keep_regular_in_family(False)
if not n.parse_ok:
    sys.exit("Something with name parsing went wrong")

# Open the file
newfont = fontforge.open(args.input)

# Rename the file
n.rename_font(newfont)

# Other information
newfont.appendSFNTName(
    "English (US)", "UniqueID", "{};{}".format(args.version, n.ps_fontname())
)
newfont.appendSFNTName("English (US)", "Trademark", "")

# The grave accent type is somehow not correctly detected;
# we want it to be an ordinary character
newfont["grave"].glyphclass="baseglyph"

# Mix our version information in
newfont.sfntRevision = None  # Auto-set (refreshed) by fontforge
newfont.appendSFNTName("English (US)", "Version", args.version)
newfont.version = args.version

if n.ps_fontname().lower().find("mono"):
    # For MS-Windows console apps
    panose = list(newfont.os2_panose)
    if panose[0] < 3:  # https://forum.high-logic.com/postedfiles/Panose.pdf
        panose[3] = 9  # 3 (4th value) = propotion: 9 = monospaced
        newfont.os2_panose = tuple(panose)

# Save
newfont.generate(args.output)
print(
    "Generated '{}' from {} version {}".format(args.output, n.fullname(), args.version)
)
